### ISSUE TITLE
ReferenceError at initialisation logic flash of unstyled content (1.16.13)

### ISSUE THREAD

**Issue by myurtsev** [johannschopplich/animere#1]
First of all thank you for this package, love to use it.

I'm having the following issue however on version 1.6.13 after changing the initialisation logic of Fauc:

`root.dataset.animatable = "true";`
causes the following error: `ReferenceError: Can't find variable: root`

But besides this error, do we really need this initialisation logic? It seems to work fine without it, no flashing for me at least. But haven't really tested it through.

**Comment by myurtsev** [comment]
Working with: `document.documentElement.dataset.animatable = "true";`

**Comment by johannschopplich** [comment]
Hey there! Foremost, let me tell you, how happy I am to hear that this library actually is used. 🙂 I fixed the README instructions. `root` was a leftover, should be `document.documentElement`.

You only have to use this initialization logic, if you actually encounter FOUC. It's optional.
